/**
 *      -- Java Garbage Collection
 * 
 * The Java Garbage Collector (GC) is an automatic memory management system within 
 * the Java Virtual Machine (JVM). Its primary function is to automatically reclaim 
 * memory occupied by objects that are no longer referenced by the running Java 
 * application, thus preventing memory leaks and simplifying memory management for 
 * developers.
 * 
 *      -- class
 * In Java, a class serves as a blueprint or a template for creating objects. 
 * It defines the structure and behavior that objects of that class will possess.
 *  Instances of a class are objects
 * 
 */

// Declare class
/* public */ class Counter {
    private int value;
    public void inc() {
        ++value;
    }
    public int getValue() {
        return value;
    }
}

// Declaring attribute
/* public */ class Foo {
    private int x;
    private float f = 0.0;
    private String name = "Anonymous";
}

// Declaring methods
/* public */ class Counter {
    public static final int MAX = 100;
    private int value;
    public void inc() {
        if (value < MAX) {
            ++value;
        }
    }
    public int getValue() {
        return value;
    }
}

/**
 *      -- Constructors
 * 
 * Role: Object initialization
 * Name must be the same as class name
 * Must not have return type
 * Every class should have at least one constructor
 *      if dont compiler will genarate the default constructor
 * Usually declared in public
 * One class can have more than one constructor
 *      it call constructor overloarding
 */


/**
 *      -- Deafault constructors
 * Always least one constructor in ever class
 * If we did not write the constructor, the default constructor is generated by the compiler.
 *      this constructor takes no argument
 *      the body is empty
 * 
 */

/* public */ class Date {
    private int year, month, day;
    
    public Date() { // <--- default constructor

    }
}

/**
 *      -- Objects
 * Objecs are instances of classes
 * Allocated on the heap by using the new operator
 * Constructor is invoked automaticaly on the new object
 * 
 */

// Eg: -
Counter conter = new Counter();

Date date1 =  new Date(2016, 9, 23);

Person person = new Person("Sachintha", "Piyathunga");


/**
 *      -- Packages
 * Halps to manage the large software systems
 * Contains: classes, sub-packeges
 * 
 */


/**
 *      -- Java Types
 *  - Primitive 
 *      * Logical - boolean
 *      * Textual - char
 *      * Integral -  byte, sort, int , long
 */
































public class Jtut1 {
    
}
